services:
  airflow-standalone:
    image: apache/airflow:latest
    container_name: airflow-standalone
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config
      - ./data:/opt/airflow/data
      - ./src:/opt/airflow/src   


    env_file:
      - .env

    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__WEBSERVER__DEFAULT_UI_LOCALE=en
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin

    command: standalone
    restart: always
